// <auto-generated />
namespace FeriasFacil.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ffv11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ffv11));
        
        string IMigrationMetadata.Id
        {
            get { return "201411181634257_ffv1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
